Repository WaykiChain/WaykiChain, pull requests merged in 2019-04, with the labels that each got.

#152 refactor: make RegID optional
  src/database.cpp
  src/main.h
  src/miner.cpp
  src/rpc/rpcblockchain.cpp
  src/rpc/rpcmisc.cpp
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
  src/test/appacc_test.cpp
  src/test/systestscript.cpp
  src/tx.cpp
  src/tx.h
  src/txdb.cpp
  src/vm/appaccount.h
  src/vm/lmylib.cpp
  src/vm/vmrunenv.cpp
  src/vm/vmrunenv.h
Labels: enhancement

#153 avoid warning
  src/database.h
  src/rpc/rpcmisc.cpp
Labels: avoid warning

#154 Implementation of RPC HTTP server uses libevent to replace boost::asio
  Docker/WaykiChain.conf
  configure.ac
  src/Makefile.am
  src/coind.cpp
  src/init.cpp
  src/init.h
  src/netbase.cpp
  src/netbase.h
  src/rpc/httpserver.cpp
  src/rpc/httpserver.h
  src/rpc/rpcprotocol.h
  src/rpc/rpcserver.cpp
  src/rpc/rpcserver.h
  src/rpc/rpcwallet.cpp
  src/support/events.h
  src/sync.h
  src/util.cpp
  src/util.h
Labels: rpc

#156 limit to 65K for rawtx in sendrawtx rpc
  src/rpc/rpctx.cpp
Labels: rpc

#155 performance: improve tps
  src/crypter.cpp
  src/crypter.h
  src/cuiserver.cpp
  src/cuiserver.h
  src/database.cpp
  src/database.h
  src/init.cpp
  src/init.h
  src/keystore.cpp
  src/keystore.h
  src/main.cpp
  src/main.h
  src/messagequeue.h
  src/miner.cpp
  src/net.cpp
  src/noui.cpp
  src/rpc/rpcblockchain.cpp
  src/rpc/rpcdump.cpp
  src/rpc/rpcmisc.cpp
  src/rpc/rpcrawtransaction.cpp
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
  src/sync.h
  src/test/scriptdb_tests.cpp
  src/tx.cpp
  src/tx.h
  src/txdb.cpp
  src/txdb.h
  src/txmempool.cpp
  src/ui_interface.h
  src/uint256.h
  src/util.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: enhancement, tps

#157 rename macro
  src/messagequeue.h
Labels: style

#158 format && naming
  src/database.cpp
  src/database.h
  src/miner.cpp
  src/rpc/rpctx.cpp
  src/txdb.cpp
  src/txdb.h
  src/uint256.h
Labels: style

#162 Fix the compile error and warning
  src/net.cpp
  src/tinyformat.h
  src/util.cpp
Labels: compile error

#161 refactor SignatureHash
  src/tx.h
Labels: enhancement, tps

#163 adjust message queue size according to <period, batchSize>
  src/messagequeue.h
  src/rpc/rpcblockchain.cpp
  src/rpc/rpcclient.cpp
Labels: enhancement, rpc

#169 improve flow && format
  src/rpc/rpctx.cpp
  src/rpc/rpcvm.cpp
  src/rpc/rpcwallet.cpp
Labels: style

#171 feature: support multisig transaction
  src/accounts/accounts.h
  src/base58.cpp
  src/base58.h
  src/chainparams.h
  src/key.h
  src/keystore.cpp
  src/keystore.h
  src/main.cpp
  src/main.h
  src/miner.h
  src/rpc/rpcclient.cpp
  src/rpc/rpcmisc.cpp
  src/rpc/rpcserver.cpp
  src/rpc/rpcserver.h
  src/rpc/rpctx.cpp
  src/rpc/rpcvm.cpp
  src/rpc/rpcwallet.cpp
  src/serialize.h
  src/tx.cpp
  src/tx.h
  src/wallet/wallet.h
Labels: enhancement, rpc

#172 update copyright
  src/base58.cpp
  src/base58.h
Labels: copyright

#173 support multisig transaction for related rpcs
  src/rpc/rpctx.cpp
  src/tx/tx.cpp
  src/wallet/wallet.h
Labels: enhancement, rpc

#175 improve validateaddr help message && modify return key
  src/rpc/rpctx.cpp
Labels: rpc, style

#176 feature: add createmultisig rpc
  src/accounts/key.h
  src/rpc/rpcclient.cpp
  src/rpc/rpcserver.cpp
  src/rpc/rpcserver.h
  src/rpc/rpcwallet.cpp
Labels: enhancement, multisig, rpc

#177 feature: add genmultisigraw rpc
  src/accounts/key.h
  src/main.h
  src/rpc/rpcclient.cpp
  src/rpc/rpcserver.cpp
  src/rpc/rpcserver.h
  src/rpc/rpcwallet.cpp
  src/tx/tx.cpp
  src/tx/tx.h
Labels: enhancement, multisig, rpc

#178 naming
  src/rpc/rpcclient.cpp
  src/rpc/rpcserver.cpp
  src/rpc/rpcserver.h
  src/rpc/rpctx.cpp
Labels: rpc, style

#179 naming
  src/rpc/rpcclient.cpp
  src/rpc/rpcserver.cpp
  src/rpc/rpcserver.h
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
Labels: style

#180 support multisig in signtxraw
  src/main.cpp
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
  src/tx/tx.cpp
  src/tx/tx.h
  src/wallet/wallet.h
Labels: enhancement, multisig, rpc

#181 add coinlua program for test coin lua more easily
  configure.ac
  src/Makefile.am
  src/vm/lua/coinlua.c
Labels: vm

#182 improve signtxraw rpc to satisfy mulsig transaction
  docs/CmdHelp.md
  src/main.cpp
  src/noui.cpp
  src/rpc/rpcclient.cpp
  src/rpc/rpcmisc.cpp
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
  src/tx/tx.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
Labels: enhancement, mulsig, rpc

#183 improve error message in rpc
  src/rpc/rpcmining.cpp
  src/rpc/rpctx.cpp
  src/rpc/rpcvm.cpp
  src/wallet/wallet.cpp
Labels: style

#184 fix the compile warn of switch case
  .gitignore
  src/crypto/hash.cpp
Labels: avoid warning

#185 add "\n" for log message in the events.cpp
  src/support/events.cpp
Labels: style

#187 fix: fail to check 0-1 ~ 0-12 accounts' regid
  src/accounts/accounts.cpp
Labels: bug, rpc

#186 fix: signtxraw rpc signature error in mulsig transaction
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
  src/tx/tx.cpp
Labels: bug, mulsig, rpc

#188 feature: add decodemulsigscript to decode mulsig script
  src/accounts/key.h
  src/accounts/keystore.cpp
  src/accounts/keystore.h
  src/main.cpp
  src/miner/miner.h
  src/rpc/rpcmisc.cpp
  src/rpc/rpcserver.cpp
  src/rpc/rpcserver.h
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
  src/tx/tx.cpp
  src/tx/tx.h
  src/wallet/wallet.h
Labels: mulsig, rpc

#190 fix compile error
  src/rpc/rpctx.cpp
Labels: compile error

#189 format
  src/tx/tx.cpp
Labels: style

#191 refactor: CMulsigTx::UndoExecuteTx
  src/rpc/rpcwallet.cpp
  src/tx/tx.cpp
  src/tx/tx.h
Labels: enhancement, mulsig

#192 fix: failed to start coind caused by unnecessary check in delegatevotetx
  src/tx/tx.cpp
Labels: bug

#194 Change the implements of CUserID to avoid compile error in ubuntu 14.04
  src/accounts/accounts.cpp
  src/accounts/id.h
  src/accounts/vote.h
  src/database.cpp
  src/main.cpp
  src/rpc/rpcnet.cpp
  src/rpc/rpctx.cpp
  src/tx/tx.cpp
  src/tx/tx.h
  src/vm/lmylib.cpp
  src/vm/vmrunenv.cpp
Labels: compile error

#195 fix: failed to start coind caused by unnecessary votecount check
  src/configuration.h
  src/tx/tx.cpp
Labels: bug

#196 docs: update build-unix
  docs/build-unix.md
Labels: docs

#197 fix: check whether the delegate account is registered
  src/accounts/vote.h
  src/rpc/rpctx.cpp
  src/tx/tx.cpp
Labels: bug, rpc

#198 check height in genxxxraw rpc
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
Labels: enhancement, rpc

#199 refactor: UndoExecuteTx
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
  src/tx/stablecoin.h
  src/tx/tx.cpp
  src/tx/tx.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: refactor

#201 add fuel calculation for memory and store of lua vm
  src/Makefile.am
  src/vm/lmylib.cpp
  src/vm/lua/coinlua.c
  src/vm/lua/lburner.c
  src/vm/lua/lburner.h
  src/vm/lua/lmem.c
  src/vm/lua/lstate.c
  src/vm/lua/lstate.h
  src/vm/lua/lua.h
  src/vm/lua/lua.hpp
  src/vm/lua/lvm.c
  src/vm/vmlua.cpp
  src/vm/vmlua.h
  src/vm/vmrunenv.cpp
  src/vm/vmrunenv.h
Labels: enhancement, vm

#202 fix: ajust time correctly according to block interval
  src/chainparams.h
  src/main.cpp
  src/util.cpp
Labels: bug

#203 fix: add softfork to check whether the voted account is registered
  src/tx/tx.cpp
  src/vm/lmylib.cpp
  src/vm/vmrunenv.cpp
  src/vm/vmrunenv.h
Labels: bug, enhancement
