Repository WaykiChain/WaykiChain, pull requests merged in 2019-05, with the labels that each got.

#205 fix the compile error for coinlua in ubuntu14.04
  src/Makefile.am
Labels: compile error

#206 fix: failed to start node caused by uninitialized class member variables
  src/accounts/accounts.cpp
  src/accounts/accounts.h
  src/main.cpp
  src/main.h
  src/tx/tx.cpp
  src/tx/tx.h
Labels: bug

#207 refactor
  src/accounts/accounts.h
  src/accounts/vote.h
  src/rpc/rpctx.cpp
  src/tx/accountreg.h
  src/tx/bcoin.h
  src/tx/contract.h
  src/tx/delegate.h
  src/tx/tx.h
Labels: refactor, rpc, style

#209 fix: cache error
  src/accounts/accounts.cpp
  src/accounts/accounts.h
  src/chainparams.cpp
  src/database.cpp
  src/database.h
  src/main.cpp
  src/miner/miner.cpp
  src/rpc/rpcblockchain.cpp
  src/rpc/rpcmisc.cpp
  src/rpc/rpctx.cpp
  src/rpc/rpcwallet.cpp
  src/tx/accountreg.h
  src/tx/pricefeed.cpp
  src/tx/txmempool.cpp
  src/tx/txmempool.h
  src/wallet/wallet.cpp
Labels: bug, refactor

#208 support to calculate fuel for lua operators
  src/vm/lua/coinlua.c
  src/vm/lua/lburner.c
  src/vm/lua/lburner.h
  src/vm/lua/lvm.c
Labels: vm

#210 fix: assertion error
  src/chainparams.cpp
Labels: bug, compile error

#212 improve flow && format
  src/main.cpp
  src/miner/miner.cpp
  src/tx/delegatetx.cpp
Labels: refactor, style

#213 make the unit test compile correctly
  .gitignore
  configure.ac
  src/Makefile.am
  src/Makefile_test.am
  src/test/DoS_tests.cpp
  src/test/Makefile.am
  src/test/account_tests.cpp
  src/test/accountview_tests.cpp
  src/test/appacc_test.cpp
  src/test/base58_tests.cpp
  src/test/bloom_tests.cpp
  src/test/canonical_tests.cpp
  src/test/chainparams_tests.cpp
  src/test/checkblock_tests.cpp
  src/test/key_tests.cpp
  src/test/main_tests.cpp
  src/test/pressure_tests.cpp
  src/test/scriptdb_tests.cpp
  src/test/scriptdbex_tests.cpp
  src/test/system_test.cpp
  src/test/systemacct_test.cpp
  src/test/systestbase.cpp
  src/test/systestscript.cpp
  src/test/test_coin.cpp
Labels: test

#214 failed to erase vote due to invalid regid
  src/accounts/account.cpp
  src/accounts/account.h
  src/accounts/id.h
  src/configuration.h
  src/init.cpp
  src/init.h
  src/main.cpp
  src/miner/miner.cpp
  src/noui.cpp
  src/persistence/contractdb.cpp
  src/rpc/rpcblockchain.cpp
  src/rpc/rpcdump.cpp
  src/rpc/rpcmining.cpp
  src/rpc/rpcmisc.cpp
  src/rpc/rpcserver.cpp
  src/rpc/rpctx.cpp
  src/rpc/rpcvm.cpp
  src/rpc/rpcwallet.cpp
  src/test/betroll_test.cpp
  src/test/pressure_tests.cpp
  src/test/system_test.cpp
  src/test/systestbase.cpp
  src/test/test_coin.cpp
  src/tx/contracttx.cpp
  src/tx/delegatetx.cpp
  src/vm/vmrunenv.cpp
  src/vm/vmrunenv.h
Labels: bug, refactor, style

#215 change BURN_VER_R2 to 10002
  src/vm/lua/lburner.h
Labels: bug

#217 delete the src/test/Makefile from configure.ac
  configure.ac
Labels: compile error

#216 fix: ensure forward compatibility for one coin one vote
  src/accounts/account.cpp
  src/accounts/account.h
  src/commons/messagequeue.h
  src/configuration.h
  src/tx/delegatetx.cpp
  src/tx/fcoinstaketx.h
  src/tx/scointx.h
  src/tx/tx.cpp
  src/vm/vmrunenv.cpp
Labels: bug

#218 fix: compilation error caused by missing file
  src/tx/fcoinstaketx.cpp
Labels: compile error

#219 refactor && improve flow
  src/commons/limitedmap.h
  src/main.cpp
  src/miner/miner.cpp
  src/miner/miner.h
  src/persistence/accountdb.cpp
  src/persistence/accountdb.h
  src/persistence/block.cpp
  src/persistence/block.h
  src/persistence/blockdb.cpp
  src/persistence/blockdb.h
  src/persistence/contractdb.cpp
  src/persistence/contractdb.h
  src/persistence/leveldbwrapper.cpp
  src/persistence/leveldbwrapper.h
  src/persistence/pricefeeddb.cpp
  src/persistence/pricefeeddb.h
  src/persistence/syncdata.cpp
  src/persistence/syncdata.h
  src/persistence/syncdatadb.cpp
  src/persistence/syncdatadb.h
  src/persistence/txdb.cpp
  src/persistence/txdb.h
  src/rpc/rpctx.cpp
Labels: bug, refactor, style

#220 refactor: CTransactionDBCache
  src/init.cpp
  src/main.cpp
  src/main.h
  src/persistence/txdb.cpp
  src/persistence/txdb.h
  src/rpc/rpctx.cpp
Labels: refactor

#221 fix: compilation error
  src/main.cpp
  src/tx/pricefeedtx.h
Labels: compilation error

#222 Modified fuel calculations to be fully compatible with version v1
  src/Makefile.am
  src/vm/lua/fuel.h
  src/vm/lua/lapi.c
  src/vm/lua/lbaselib.c
  src/vm/lua/lburner.h
  src/vm/lua/ldebug.c
  src/vm/lua/ldo.c
  src/vm/lua/ldo.h
  src/vm/lua/lgc.c
  src/vm/lua/lstate.c
  src/vm/lua/ltm.c
  src/vm/lua/lua.h
  src/vm/lua/lvm.c
  src/vm/lua/lvm.h
  src/vm/vmlua.cpp
Labels: vm

#223 Limit lua's unnecessary functionality, such as package-related and collectgarbage
  src/vm/lmylib.cpp
  src/vm/lua/lbaselib.c
  src/vm/lua/luaconf.h
  src/vm/vmlua.cpp
Labels: vm

#224 fix: parse voteType error
  src/rpc/rpctx.cpp
Labels: bug, rpc

#225 feature: set featureforkheight in regtest via configuration item
  src/chainparams.cpp
  src/chainparams.h
  src/configuration.cpp
  src/configuration.h
Labels: enhancement

#227 refactor: delegate vote storage
  src/Makefile.am
  src/main.cpp
  src/main.h
  src/persistence/contractdb.h
  src/persistence/stakedb.cpp
  src/persistence/stakedb.h
  src/tx/accountregtx.cpp
  src/tx/bcointx.cpp
  src/tx/blockrewardtx.cpp
  src/tx/contracttx.cpp
  src/tx/delegatetx.cpp
  src/tx/fcoinstaketx.cpp
  src/tx/mulsigtx.cpp
  src/tx/tx.cpp
  src/tx/tx.h
Labels: enhancement, refactor

#228 add fuel calculation for functions of mylib
  src/vm/lmylib.cpp
  src/vm/lua/fuel.h
  src/vm/lua/lburner.c
  src/vm/lua/lburner.h
  src/vm/vmlua.cpp
Labels: vm

#226 feature: make RegID optional in contract invoke transaction
  docs/CmdHelp.md
  src/main.cpp
  src/rpc/rpcblockchain.cpp
  src/rpc/rpcclient.cpp
  src/rpc/rpctx.cpp
  src/rpc/rpcvm.cpp
  src/rpc/rpcwallet.cpp
  src/tx/bcointx.cpp
  src/tx/bcointx.h
  src/tx/contracttx.cpp
  src/tx/contracttx.h
  src/tx/tx.h
  src/vm/lmylib.cpp
  src/vm/vmrunenv.cpp
  src/vm/vmrunenv.h
Labels: enhancement, refactor

#229 feature: reward profits in every block
  src/accounts/account.cpp
  src/accounts/account.h
  src/main.cpp
  src/miner/miner.cpp
  src/miner/miner.h
  src/tx/blockrewardtx.cpp
Labels: enhancement

#230 improve getblock rpc
  src/rpc/rpcblockchain.cpp
  src/rpc/rpcclient.cpp
  src/rpc/rpcclient.h
  src/tx/bcointx.cpp
  src/tx/contracttx.cpp
Labels: rpc

#231 Improve the implementation of fcoinstaketx
  src/tx/fcoinstaketx.cpp
  src/tx/fcoinstaketx.h
Labels: enhancement

#233 fix: failed to deploy contract due to low fees/Kb
  src/accounts/account.cpp
  src/accounts/account.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner/miner.cpp
  src/persistence/accountdb.cpp
  src/rpc/rpcblockchain.cpp
  src/rpc/rpcdump.cpp
  src/rpc/rpcserver.cpp
  src/rpc/rpcserver.h
  src/rpc/rpctx.cpp
  src/rpc/rpcvm.cpp
  src/tx/accountregtx.cpp
  src/tx/bcointx.cpp
  src/tx/blockpricemediantx.cpp
  src/tx/blockrewardtx.cpp
  src/tx/contracttx.cpp
  src/tx/delegatetx.cpp
  src/tx/tx.cpp
  src/tx/txmempool.cpp
  src/vm/vmlua.cpp
  src/vm/vmrunenv.cpp
  src/vm/vmrunenv.h
Labels: bug, rpc

#234 refactor: remove ui module
  Docker/WaykiChain.conf
  src/Makefile.am
  src/accounts/cdp.h
  src/alert.cpp
  src/coind-cli.cpp
  src/coind.cpp
  src/crypter.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/net.cpp
  src/noui.cpp
  src/noui.h
  src/persistence/block.h
  src/ptest/CreateMinterKey_tests.cpp
  src/ptest/P_test.cpp
  src/rpc/httpserver.cpp
  src/rpc/rpcclient.cpp
  src/rpc/rpcserver.cpp
  src/test/system_test.cpp
  src/test/systestbase.cpp
  src/test/systestbase.h
  src/test/systestscript.cpp
  src/test/test_coin.cpp
  src/tx/txmempool.cpp
  src/ui_interface.h
  src/util.cpp
  src/util.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: refactor
